---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: devos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: kargs
    kargs:
      - zswap.enabled=1
      - zswap.compressor=zstd
      - zswap.zpool=z3fold
      - zswap.max_pool_percent=25

  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://packages.microsoft.com/yumrepos/vscode/config.repo
      copr:
        - atim/starship
    install:
      packages:
        - atuin
        - chezmoi
        - alacritty
        - ripgrep
        - tmux
        - btop
        - micro
        - starship
        - niri
        - noctalia-shell
        - lazygit
        - code
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - waybar
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: systemd
    system:
      enabled:
        - create-swapfile.service
      masked:
        - systemd-zram-setup@zram0.service
    user:
      enabled:
        - niri.service
        - noctalia.service

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
          - com.slack.Slack
          - com.jetbrains.Rider
          - com.vivaldi.Vivaldi
          - com.bitwarden.desktop
          - org.telegram.desktop
          - com.microsoft.AzureStorageExplorer
          - com.discordapp.Discord
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - com.usebottles.bottles
          - com.github.Matoking.protontricks
          - com.github.tchx84.Flatseal
          - net.lutris.Lutris
          - md.obsidian.Obsidian
          - org.libreoffice.LibreOffice
          - org.gnome.Boxes
          - io.podman_desktop.PodmanDesktop
      - scope: user # Also add Flathub user repo, but no user packages

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: chezmoi
    repository: "https://github.com/pmd-coutinho/dotfiles" # my dotfiles repo
    all-users: false # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo

  - type: initramfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
